const MINUTES_IN_HOUR = 60;
const SECONDS_IN_MINUTE = 60;
export const MILLISECONDS_IN_SECOND = 1000;
export const NANOSECONDS_IN_MILLISECOND = 1_000_000;

const FIFTEEN_MINUTES = 15;
const THIRTY_MINUTES = 30;

export const SIGNUP_RATE_LIMITER_TIME = MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND; // 1 hour
export const LOGIN_RATE_LIMITER_TIME = FIFTEEN_MINUTES * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND; // 15 minutes
export const PASSWORD_RESET_RATE_LIMITER_TIME = MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND; // 1 hour
export const RESPONSE_TIME_IN_MILLISECONDS = MILLISECONDS_IN_SECOND * NANOSECONDS_IN_MILLISECOND;
export const TWENTY_FOUR_HOURS_IN_MILLISECONDS = MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
export const THIRTY_MINUTES_IN_MILLISECONDS = THIRTY_MINUTES * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
export const MINUTES_IN_MILLISECONDS = MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;
