import { createRouter, RouterProvider } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

import { useSelector } from 'react-redux';
import { RootState } from './store';
import { PageLoader } from './components/ui/page-loader.component';
import NotFound from './pages/NotFound';

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

// Create a new router instance
// @ts-expect-error - routeTree is generated by tanstack-router-plugin
const router = createRouter({
  routeTree,
  defaultPendingComponent: () => <PageLoader spinning={true} />,
  defaultNotFoundComponent: () => <NotFound />,
  context: {
    currentUser: null,
  },
});

export default function App() {
  const tokens = useSelector((state: RootState) => state.user.tokens);

  return <RouterProvider router={router} context={{ tokens }} />;
}
