/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password/index'
import { Route as AuthRegistrationIndexRouteImport } from './routes/_auth/registration/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthForgotPasswordIndexRouteImport } from './routes/_auth/forgot-password/index'
import { Route as AuthConfirmMailIndexRouteImport } from './routes/_auth/confirm-mail/index'
import { Route as AppCrmIndexRouteImport } from './routes/_app/crm/index'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/_auth/reset-password/$token'
import { Route as AuthConfirmEmailTokenRouteImport } from './routes/_auth/confirm-email/$token'
import { Route as AppCrmDashboardRouteImport } from './routes/_app/crm/dashboard'
import { Route as AppCrmTasksIndexRouteImport } from './routes/_app/crm/tasks/index'
import { Route as AppCrmSegmentsIndexRouteImport } from './routes/_app/crm/segments/index'
import { Route as AppCrmLeadsIndexRouteImport } from './routes/_app/crm/leads/index'
import { Route as AppCrmInsightsIndexRouteImport } from './routes/_app/crm/insights/index'
import { Route as AppCrmCommunicationIndexRouteImport } from './routes/_app/crm/communication/index'
import { Route as AppCrmBookingsIndexRouteImport } from './routes/_app/crm/bookings/index'
import { Route as AppCrmTasksNewRouteImport } from './routes/_app/crm/tasks/new'
import { Route as AppCrmLeadsNewRouteImport } from './routes/_app/crm/leads/new'
import { Route as AppCrmLeadsIdRouteImport } from './routes/_app/crm/leads/$id'
import { Route as AppCrmCommunicationNewRouteImport } from './routes/_app/crm/communication/new'
import { Route as AppCrmBookingsNewRouteImport } from './routes/_app/crm/bookings/new'
import { Route as AppCrmTasksNewLeadIdRouteImport } from './routes/_app/crm/tasks/new.$leadId'
import { Route as AppCrmLeadsEditIdRouteImport } from './routes/_app/crm/leads/edit.$id'
import { Route as AppCrmCommunicationNewLeadIdRouteImport } from './routes/_app/crm/communication/new.$leadId'
import { Route as AppCrmBookingsNewLeadIdRouteImport } from './routes/_app/crm/bookings/new.$leadId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegistrationIndexRoute = AuthRegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordIndexRoute = AuthForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmMailIndexRoute = AuthConfirmMailIndexRouteImport.update({
  id: '/confirm-mail/',
  path: '/confirm-mail/',
  getParentRoute: () => AuthRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailTokenRoute = AuthConfirmEmailTokenRouteImport.update({
  id: '/confirm-email/$token',
  path: '/confirm-email/$token',
  getParentRoute: () => AuthRoute,
} as any)
const AppCrmDashboardRoute = AppCrmDashboardRouteImport.update({
  id: '/crm/dashboard',
  path: '/crm/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmTasksIndexRoute = AppCrmTasksIndexRouteImport.update({
  id: '/crm/tasks/',
  path: '/crm/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmSegmentsIndexRoute = AppCrmSegmentsIndexRouteImport.update({
  id: '/crm/segments/',
  path: '/crm/segments/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsIndexRoute = AppCrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmInsightsIndexRoute = AppCrmInsightsIndexRouteImport.update({
  id: '/crm/insights/',
  path: '/crm/insights/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCommunicationIndexRoute =
  AppCrmCommunicationIndexRouteImport.update({
    id: '/crm/communication/',
    path: '/crm/communication/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCrmBookingsIndexRoute = AppCrmBookingsIndexRouteImport.update({
  id: '/crm/bookings/',
  path: '/crm/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmTasksNewRoute = AppCrmTasksNewRouteImport.update({
  id: '/crm/tasks/new',
  path: '/crm/tasks/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsNewRoute = AppCrmLeadsNewRouteImport.update({
  id: '/crm/leads/new',
  path: '/crm/leads/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsIdRoute = AppCrmLeadsIdRouteImport.update({
  id: '/crm/leads/$id',
  path: '/crm/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCommunicationNewRoute = AppCrmCommunicationNewRouteImport.update({
  id: '/crm/communication/new',
  path: '/crm/communication/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmBookingsNewRoute = AppCrmBookingsNewRouteImport.update({
  id: '/crm/bookings/new',
  path: '/crm/bookings/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmTasksNewLeadIdRoute = AppCrmTasksNewLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppCrmTasksNewRoute,
} as any)
const AppCrmLeadsEditIdRoute = AppCrmLeadsEditIdRouteImport.update({
  id: '/crm/leads/edit/$id',
  path: '/crm/leads/edit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCommunicationNewLeadIdRoute =
  AppCrmCommunicationNewLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AppCrmCommunicationNewRoute,
  } as any)
const AppCrmBookingsNewLeadIdRoute = AppCrmBookingsNewLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => AppCrmBookingsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/crm/dashboard': typeof AppCrmDashboardRoute
  '/confirm-email/$token': typeof AuthConfirmEmailTokenRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/crm': typeof AppCrmIndexRoute
  '/confirm-mail': typeof AuthConfirmMailIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/crm/bookings/new': typeof AppCrmBookingsNewRouteWithChildren
  '/crm/communication/new': typeof AppCrmCommunicationNewRouteWithChildren
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/leads/new': typeof AppCrmLeadsNewRoute
  '/crm/tasks/new': typeof AppCrmTasksNewRouteWithChildren
  '/crm/bookings': typeof AppCrmBookingsIndexRoute
  '/crm/communication': typeof AppCrmCommunicationIndexRoute
  '/crm/insights': typeof AppCrmInsightsIndexRoute
  '/crm/leads': typeof AppCrmLeadsIndexRoute
  '/crm/segments': typeof AppCrmSegmentsIndexRoute
  '/crm/tasks': typeof AppCrmTasksIndexRoute
  '/crm/bookings/new/$leadId': typeof AppCrmBookingsNewLeadIdRoute
  '/crm/communication/new/$leadId': typeof AppCrmCommunicationNewLeadIdRoute
  '/crm/leads/edit/$id': typeof AppCrmLeadsEditIdRoute
  '/crm/tasks/new/$leadId': typeof AppCrmTasksNewLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/crm/dashboard': typeof AppCrmDashboardRoute
  '/confirm-email/$token': typeof AuthConfirmEmailTokenRoute
  '/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/crm': typeof AppCrmIndexRoute
  '/confirm-mail': typeof AuthConfirmMailIndexRoute
  '/forgot-password': typeof AuthForgotPasswordIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/crm/bookings/new': typeof AppCrmBookingsNewRouteWithChildren
  '/crm/communication/new': typeof AppCrmCommunicationNewRouteWithChildren
  '/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/crm/leads/new': typeof AppCrmLeadsNewRoute
  '/crm/tasks/new': typeof AppCrmTasksNewRouteWithChildren
  '/crm/bookings': typeof AppCrmBookingsIndexRoute
  '/crm/communication': typeof AppCrmCommunicationIndexRoute
  '/crm/insights': typeof AppCrmInsightsIndexRoute
  '/crm/leads': typeof AppCrmLeadsIndexRoute
  '/crm/segments': typeof AppCrmSegmentsIndexRoute
  '/crm/tasks': typeof AppCrmTasksIndexRoute
  '/crm/bookings/new/$leadId': typeof AppCrmBookingsNewLeadIdRoute
  '/crm/communication/new/$leadId': typeof AppCrmCommunicationNewLeadIdRoute
  '/crm/leads/edit/$id': typeof AppCrmLeadsEditIdRoute
  '/crm/tasks/new/$leadId': typeof AppCrmTasksNewLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/crm/dashboard': typeof AppCrmDashboardRoute
  '/_auth/confirm-email/$token': typeof AuthConfirmEmailTokenRoute
  '/_auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_auth/confirm-mail/': typeof AuthConfirmMailIndexRoute
  '/_auth/forgot-password/': typeof AuthForgotPasswordIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/registration/': typeof AuthRegistrationIndexRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/_app/crm/bookings/new': typeof AppCrmBookingsNewRouteWithChildren
  '/_app/crm/communication/new': typeof AppCrmCommunicationNewRouteWithChildren
  '/_app/crm/leads/$id': typeof AppCrmLeadsIdRoute
  '/_app/crm/leads/new': typeof AppCrmLeadsNewRoute
  '/_app/crm/tasks/new': typeof AppCrmTasksNewRouteWithChildren
  '/_app/crm/bookings/': typeof AppCrmBookingsIndexRoute
  '/_app/crm/communication/': typeof AppCrmCommunicationIndexRoute
  '/_app/crm/insights/': typeof AppCrmInsightsIndexRoute
  '/_app/crm/leads/': typeof AppCrmLeadsIndexRoute
  '/_app/crm/segments/': typeof AppCrmSegmentsIndexRoute
  '/_app/crm/tasks/': typeof AppCrmTasksIndexRoute
  '/_app/crm/bookings/new/$leadId': typeof AppCrmBookingsNewLeadIdRoute
  '/_app/crm/communication/new/$leadId': typeof AppCrmCommunicationNewLeadIdRoute
  '/_app/crm/leads/edit/$id': typeof AppCrmLeadsEditIdRoute
  '/_app/crm/tasks/new/$leadId': typeof AppCrmTasksNewLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/crm/dashboard'
    | '/confirm-email/$token'
    | '/reset-password/$token'
    | '/crm'
    | '/confirm-mail'
    | '/forgot-password'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/crm/bookings/new'
    | '/crm/communication/new'
    | '/crm/leads/$id'
    | '/crm/leads/new'
    | '/crm/tasks/new'
    | '/crm/bookings'
    | '/crm/communication'
    | '/crm/insights'
    | '/crm/leads'
    | '/crm/segments'
    | '/crm/tasks'
    | '/crm/bookings/new/$leadId'
    | '/crm/communication/new/$leadId'
    | '/crm/leads/edit/$id'
    | '/crm/tasks/new/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/crm/dashboard'
    | '/confirm-email/$token'
    | '/reset-password/$token'
    | '/crm'
    | '/confirm-mail'
    | '/forgot-password'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/crm/bookings/new'
    | '/crm/communication/new'
    | '/crm/leads/$id'
    | '/crm/leads/new'
    | '/crm/tasks/new'
    | '/crm/bookings'
    | '/crm/communication'
    | '/crm/insights'
    | '/crm/leads'
    | '/crm/segments'
    | '/crm/tasks'
    | '/crm/bookings/new/$leadId'
    | '/crm/communication/new/$leadId'
    | '/crm/leads/edit/$id'
    | '/crm/tasks/new/$leadId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/crm/dashboard'
    | '/_auth/confirm-email/$token'
    | '/_auth/reset-password/$token'
    | '/_app/crm/'
    | '/_auth/confirm-mail/'
    | '/_auth/forgot-password/'
    | '/_auth/login/'
    | '/_auth/registration/'
    | '/_auth/reset-password/'
    | '/_app/crm/bookings/new'
    | '/_app/crm/communication/new'
    | '/_app/crm/leads/$id'
    | '/_app/crm/leads/new'
    | '/_app/crm/tasks/new'
    | '/_app/crm/bookings/'
    | '/_app/crm/communication/'
    | '/_app/crm/insights/'
    | '/_app/crm/leads/'
    | '/_app/crm/segments/'
    | '/_app/crm/tasks/'
    | '/_app/crm/bookings/new/$leadId'
    | '/_app/crm/communication/new/$leadId'
    | '/_app/crm/leads/edit/$id'
    | '/_app/crm/tasks/new/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/registration/': {
      id: '/_auth/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthRegistrationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password/': {
      id: '/_auth/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirm-mail/': {
      id: '/_auth/confirm-mail/'
      path: '/confirm-mail'
      fullPath: '/confirm-mail'
      preLoaderRoute: typeof AuthConfirmMailIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/reset-password/$token': {
      id: '/_auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirm-email/$token': {
      id: '/_auth/confirm-email/$token'
      path: '/confirm-email/$token'
      fullPath: '/confirm-email/$token'
      preLoaderRoute: typeof AuthConfirmEmailTokenRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/crm/dashboard': {
      id: '/_app/crm/dashboard'
      path: '/crm/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof AppCrmDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/tasks/': {
      id: '/_app/crm/tasks/'
      path: '/crm/tasks'
      fullPath: '/crm/tasks'
      preLoaderRoute: typeof AppCrmTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/segments/': {
      id: '/_app/crm/segments/'
      path: '/crm/segments'
      fullPath: '/crm/segments'
      preLoaderRoute: typeof AppCrmSegmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/leads/': {
      id: '/_app/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/insights/': {
      id: '/_app/crm/insights/'
      path: '/crm/insights'
      fullPath: '/crm/insights'
      preLoaderRoute: typeof AppCrmInsightsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/communication/': {
      id: '/_app/crm/communication/'
      path: '/crm/communication'
      fullPath: '/crm/communication'
      preLoaderRoute: typeof AppCrmCommunicationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/bookings/': {
      id: '/_app/crm/bookings/'
      path: '/crm/bookings'
      fullPath: '/crm/bookings'
      preLoaderRoute: typeof AppCrmBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/tasks/new': {
      id: '/_app/crm/tasks/new'
      path: '/crm/tasks/new'
      fullPath: '/crm/tasks/new'
      preLoaderRoute: typeof AppCrmTasksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/leads/new': {
      id: '/_app/crm/leads/new'
      path: '/crm/leads/new'
      fullPath: '/crm/leads/new'
      preLoaderRoute: typeof AppCrmLeadsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/leads/$id': {
      id: '/_app/crm/leads/$id'
      path: '/crm/leads/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AppCrmLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/communication/new': {
      id: '/_app/crm/communication/new'
      path: '/crm/communication/new'
      fullPath: '/crm/communication/new'
      preLoaderRoute: typeof AppCrmCommunicationNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/bookings/new': {
      id: '/_app/crm/bookings/new'
      path: '/crm/bookings/new'
      fullPath: '/crm/bookings/new'
      preLoaderRoute: typeof AppCrmBookingsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/tasks/new/$leadId': {
      id: '/_app/crm/tasks/new/$leadId'
      path: '/$leadId'
      fullPath: '/crm/tasks/new/$leadId'
      preLoaderRoute: typeof AppCrmTasksNewLeadIdRouteImport
      parentRoute: typeof AppCrmTasksNewRoute
    }
    '/_app/crm/leads/edit/$id': {
      id: '/_app/crm/leads/edit/$id'
      path: '/crm/leads/edit/$id'
      fullPath: '/crm/leads/edit/$id'
      preLoaderRoute: typeof AppCrmLeadsEditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/communication/new/$leadId': {
      id: '/_app/crm/communication/new/$leadId'
      path: '/$leadId'
      fullPath: '/crm/communication/new/$leadId'
      preLoaderRoute: typeof AppCrmCommunicationNewLeadIdRouteImport
      parentRoute: typeof AppCrmCommunicationNewRoute
    }
    '/_app/crm/bookings/new/$leadId': {
      id: '/_app/crm/bookings/new/$leadId'
      path: '/$leadId'
      fullPath: '/crm/bookings/new/$leadId'
      preLoaderRoute: typeof AppCrmBookingsNewLeadIdRouteImport
      parentRoute: typeof AppCrmBookingsNewRoute
    }
  }
}

interface AppCrmBookingsNewRouteChildren {
  AppCrmBookingsNewLeadIdRoute: typeof AppCrmBookingsNewLeadIdRoute
}

const AppCrmBookingsNewRouteChildren: AppCrmBookingsNewRouteChildren = {
  AppCrmBookingsNewLeadIdRoute: AppCrmBookingsNewLeadIdRoute,
}

const AppCrmBookingsNewRouteWithChildren =
  AppCrmBookingsNewRoute._addFileChildren(AppCrmBookingsNewRouteChildren)

interface AppCrmCommunicationNewRouteChildren {
  AppCrmCommunicationNewLeadIdRoute: typeof AppCrmCommunicationNewLeadIdRoute
}

const AppCrmCommunicationNewRouteChildren: AppCrmCommunicationNewRouteChildren =
  {
    AppCrmCommunicationNewLeadIdRoute: AppCrmCommunicationNewLeadIdRoute,
  }

const AppCrmCommunicationNewRouteWithChildren =
  AppCrmCommunicationNewRoute._addFileChildren(
    AppCrmCommunicationNewRouteChildren,
  )

interface AppCrmTasksNewRouteChildren {
  AppCrmTasksNewLeadIdRoute: typeof AppCrmTasksNewLeadIdRoute
}

const AppCrmTasksNewRouteChildren: AppCrmTasksNewRouteChildren = {
  AppCrmTasksNewLeadIdRoute: AppCrmTasksNewLeadIdRoute,
}

const AppCrmTasksNewRouteWithChildren = AppCrmTasksNewRoute._addFileChildren(
  AppCrmTasksNewRouteChildren,
)

interface AppRouteChildren {
  AppCrmDashboardRoute: typeof AppCrmDashboardRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppCrmBookingsNewRoute: typeof AppCrmBookingsNewRouteWithChildren
  AppCrmCommunicationNewRoute: typeof AppCrmCommunicationNewRouteWithChildren
  AppCrmLeadsIdRoute: typeof AppCrmLeadsIdRoute
  AppCrmLeadsNewRoute: typeof AppCrmLeadsNewRoute
  AppCrmTasksNewRoute: typeof AppCrmTasksNewRouteWithChildren
  AppCrmBookingsIndexRoute: typeof AppCrmBookingsIndexRoute
  AppCrmCommunicationIndexRoute: typeof AppCrmCommunicationIndexRoute
  AppCrmInsightsIndexRoute: typeof AppCrmInsightsIndexRoute
  AppCrmLeadsIndexRoute: typeof AppCrmLeadsIndexRoute
  AppCrmSegmentsIndexRoute: typeof AppCrmSegmentsIndexRoute
  AppCrmTasksIndexRoute: typeof AppCrmTasksIndexRoute
  AppCrmLeadsEditIdRoute: typeof AppCrmLeadsEditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCrmDashboardRoute: AppCrmDashboardRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppCrmBookingsNewRoute: AppCrmBookingsNewRouteWithChildren,
  AppCrmCommunicationNewRoute: AppCrmCommunicationNewRouteWithChildren,
  AppCrmLeadsIdRoute: AppCrmLeadsIdRoute,
  AppCrmLeadsNewRoute: AppCrmLeadsNewRoute,
  AppCrmTasksNewRoute: AppCrmTasksNewRouteWithChildren,
  AppCrmBookingsIndexRoute: AppCrmBookingsIndexRoute,
  AppCrmCommunicationIndexRoute: AppCrmCommunicationIndexRoute,
  AppCrmInsightsIndexRoute: AppCrmInsightsIndexRoute,
  AppCrmLeadsIndexRoute: AppCrmLeadsIndexRoute,
  AppCrmSegmentsIndexRoute: AppCrmSegmentsIndexRoute,
  AppCrmTasksIndexRoute: AppCrmTasksIndexRoute,
  AppCrmLeadsEditIdRoute: AppCrmLeadsEditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthConfirmEmailTokenRoute: typeof AuthConfirmEmailTokenRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthConfirmMailIndexRoute: typeof AuthConfirmMailIndexRoute
  AuthForgotPasswordIndexRoute: typeof AuthForgotPasswordIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegistrationIndexRoute: typeof AuthRegistrationIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailTokenRoute: AuthConfirmEmailTokenRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthConfirmMailIndexRoute: AuthConfirmMailIndexRoute,
  AuthForgotPasswordIndexRoute: AuthForgotPasswordIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegistrationIndexRoute: AuthRegistrationIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
