#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if package.json has changed
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# If package.json changed, run npm install
check_run package.json "echo '📦 package.json changed. Running npm install...' && npm install" 